### ISSUE TITLE
parse_requirements() got an unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by Arti3DPlayer** [wooyek/flask-social-blueprint#16]
```
Downloading flask-social-blueprint-0.7.1.zip
  Running setup.py egg_info for package flask-social-blueprint
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/uwsgi_default/flask_template/build/flask-social-blueprint/setup.py", line 15, in <module>
        session=uuid.uuid1()
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/var/uwsgi_default/flask_template/build/flask-social-blueprint/setup.py", line 15, in <module>

    session=uuid.uuid1()

TypeError: parse_requirements() got an unexpected keyword argument 'session'
```

**Comment by wooyek** [comment]
What version of pip are you running?

**Comment by Arti3DPlayer** [comment]
```pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)```
And i'm not using virtualenv

**Comment by wooyek** [comment]
It's an old one, please update.
